queue: "default"
job: "launch-test/wandb-launch-sweeps/job-source-wandb-launch-sweeps-examples_launch-jobs_train-launch-jobs.py:v0"
resource: "kubernetes"
scheduler:
  docker_image: "wandb/launch-agent-dev:latest"
  resource: "kubernetes"
  resource_args: { kubernetes: {}}
  num_workers: 4