queue: "default"
job: "launch-test/wandb-launch-sweeps/job-source-wandb-launch-sweeps-examples_launch-jobs_train-launch-jobs.py:v0"
resource: "local-container"
scheduler:
  docker_image: "wandb/sweep-scheduler:latest"
  resource: "local-container"
  num_workers: 4
