[tox]
minversion=4.54.0
envlist = py{310,311,312}

[testenv:py{310,311,312}]
deps =
    -r{toxinidir}/requirements.dev.txt

install_command =
    pip install {opts} {packages}

commands =
    pytest {posargs} --cov=sweeps --cov-report=term-missing:skip-covered --cov-report=xml

[coverage:paths]
source =
    src/sweeps
    .tox/*/lib/python*/site-packages/sweeps

[coverage:run]
source =
    sweeps

[coverage:report]
exclude_also =
    if TYPE_CHECKING:

[black]
deps=
    black==22.8.0

[testenv:black]
basepython = python3.10
skip_install = true
deps = {[black]deps}
commands =
    black --check src/ tests/ tools/ examples/

[testenv:format]
basepython = python3.10
skip_install = true
deps=
    pre-commit==4.6.0
commands =
    pre-commit run --all-files

[flake8]
max-line-length = 80
select = C,E,F,W,B,B950
ignore = E501, E721, W503

[testenv:flake8]
basepython=python3.10
skip_install = true
deps =
    flake8==7.3.0
commands =
    flake8 src/ tests/ tools/ examples/ {posargs}
