[tox]
minversion=4.54.0
envlist = py{310,311,312}

[python]
lint = python3.10

[testenv:py{310,311,312}]
deps =
    -r{toxinidir}/requirements.dev.txt

install_command =
    pip install {opts} {packages}

commands =
    pytest {posargs}  --cov=./ --cov-report=xml

[black]
deps=
    black==22.8.0

[testenv:black]
basepython = {[python]lint}
skip_install = true
deps = {[black]deps}
commands =
    black --check src/ tests/ tools/ examples/

[testenv:format]
basepython = {[python]lint}
skip_install = true
deps=
    pre-commit==4.6.0
commands =
    pre-commit run --all-files

[flake8]
max-line-length = 80
select = C,E,F,W,B,B950
ignore = E501, E721, W503

[testenv:flake8]
basepython = {[python]lint}
skip_install = true
deps =
    flake8==7.3.0
commands =
    flake8 src/ tests/ tools/ examples/ {posargs}
