version: 2.1

orbs:
  codecov: codecov/codecov@5.0.3

commands:
  install-uv:
    steps:
      - run:
          name: Install uv
          command: pip install uv==0.11.9
  uv-run-dev:
    parameters:
      step_name:
        type: string
        default: Run command
      command:
        type: string
    steps:
      - run:
          name: << parameters.step_name >>
          command: uv run --with-requirements requirements.dev.txt << parameters.command >>
          no_output_timeout: 60m

jobs:
  linux310:
    docker:
      - image: cimg/python:3.10
    resource_class: large
    steps:
      - checkout
      - install-uv
      - uv-run-dev:
          step_name: Run tests
          command: tox -e py310
      - codecov/upload
      - store_artifacts:
          path: prof/
      - store_test_results:
          path: .
  linux311:
    docker:
      - image: cimg/python:3.11
    resource_class: large
    steps:
      - checkout
      - install-uv
      - uv-run-dev:
          step_name: Run tests
          command: tox -e py311
      - codecov/upload
      - store_artifacts:
          path: prof/
      - store_test_results:
          path: .
  linux312:
    docker:
      - image: cimg/python:3.12
    resource_class: large
    steps:
      - checkout
      - install-uv
      - uv-run-dev:
          step_name: Run tests
          command: --with setuptools==75.8.0 tox -e py312
      - codecov/upload
      - store_artifacts:
          path: prof/
      - store_test_results:
          path: .
  linters310:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - install-uv
      - uv-run-dev:
          step_name: Run linters
          command: pre-commit run --all-files
  linters311:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - install-uv
      - uv-run-dev:
          step_name: Run linters
          command: pre-commit run --all-files
  linters312:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - install-uv
      - uv-run-dev:
          step_name: Run linters
          command: pre-commit run --all-files

workflows:
  main:
    jobs:
      - linux310
      - linux311
      - linux312
      - linters310
      - linters311
      - linters312
