version: 2.1

orbs:
  codecov: codecov/codecov@5.0.3

commands:
  uv-run-dev:
    parameters:
      step_name:
        type: string
        default: Run command
      python_version:
        type: string
      command:
        type: string
    steps:
      - run:
          name: << parameters.step_name >>
          command: uv run --no-python-downloads --python << parameters.python_version >> --with-requirements requirements.dev.txt << parameters.command >>
          no_output_timeout: 60m

jobs:
  tests:
    parameters:
      python_version:
        type: string
      tox_env:
        type: string
      extra_uv_args:
        type: string
        default: ""
      upload_coverage:
        type: boolean
        default: false
    docker:
      - image: ghcr.io/astral-sh/uv:0.11.9-python<< parameters.python_version >>-trixie
    resource_class: large
    steps:
      - checkout
      - uv-run-dev:
          step_name: Run tests
          python_version: << parameters.python_version >>
          command: << parameters.extra_uv_args >> tox -e << parameters.tox_env >>
      - when:
          condition: << parameters.upload_coverage >>
          steps:
            # Upload coverage from one Python version to avoid duplicate Codecov reports.
            # Move coverage to another version when we deprecate this one.
            - codecov/upload:
                flags: unit
            - store_artifacts:
                path: coverage.xml
                destination: coverage/coverage.xml
      - store_artifacts:
          path: prof/
      - store_test_results:
          path: test-results

  linters:
    parameters:
      python_version:
        type: string
    docker:
      - image: ghcr.io/astral-sh/uv:0.11.9-python<< parameters.python_version >>-trixie
    resource_class: medium
    steps:
      - checkout
      - uv-run-dev:
          step_name: Run linters
          python_version: << parameters.python_version >>
          command: pre-commit run --all-files

workflows:
  main:
    jobs:
      - tests:
          name: linux310
          python_version: "3.10"
          tox_env: py310
          upload_coverage: true
      - tests:
          name: linux311
          python_version: "3.11"
          tox_env: py311
      - tests:
          name: linux312
          python_version: "3.12"
          tox_env: py312
          extra_uv_args: --with setuptools==75.8.0
      - linters:
          name: linters310
          python_version: "3.10"
      - linters:
          name: linters311
          python_version: "3.11"
      - linters:
          name: linters312
          python_version: "3.12"
