queue: "default"
# You can also specify the job in the sweep config
# job: "launch-test/wandb-launch-sweeps/job-source-wandb-launch-sweeps-examples_launch-jobs_train-launch-jobs.py:v0"
resource: "local-process"
scheduler:
  resource: "local-process"
